Repository Unibeautify/unibeautify-cli, pull requests merged in 2018-07, with the labels that each got.

#26 Major refactoring, setup Jest for tests
  .gitignore
  .travis.yml
  .unibeautifyrc.yml
  jest.config.js
  package-lock.json
  package.json
  src/@types/find-global-packages/index.d.ts
  src/Runner.ts
  src/cli.ts
  src/index.ts
  test/Runner.spec.ts
  test/__snapshots__/Runner.spec.ts.snap
  test/index.spec.ts
  tsconfig.json
  tslint.json
Labels: enhancement, help wanted, high-priority

#47 Add more tests and setup CodeClimate
  .codeclimate.yml
  .travis.yml
  package-lock.json
  package.json
  src/Runner.ts
  test/.unibeautifyrc.yml
  test/Runner.spec.ts
  test/__snapshots__/Runner.spec.ts.snap
  test/mockStreams.ts
Labels: enhancement

#51 Major refactoring, add more tests
  .unibeautifyignore
  .unibeautifyrc.yml
  __mocks__/g-search.js
  jest.config.js
  package-lock.json
  package.json
  src/Runner.ts
  src/cli.ts
  src/commands/BaseCommand.ts
  src/commands/BeautifyCommand.ts
  src/commands/SupportCommand.ts
  src/utils.ts
  test/Runner.spec.ts
  test/__snapshots__/utils.spec.ts.snap
  test/commands/BeautifyCommand.spec.ts
  test/commands/SupportCommand.spec.ts
  test/commands/__snapshots__/BeautifyCommand.spec.ts.snap
  test/commands/__snapshots__/SupportCommand.spec.ts.snap
  test/fixtures/test1.js
  test/mockStreams.ts
  test/test.js
  test/utils.spec.ts
  yarn.lock
Labels: bug, enhancement

#54 Consolidate error handling, add more tests
  src/commands/BaseCommand.ts
  src/commands/BeautifyCommand.ts
  test/commands/BeautifyCommand.spec.ts
  test/commands/__snapshots__/BeautifyCommand.spec.ts.snap
Labels: enhancement

#55 Add replace file contents functionality
  src/cli.ts
  src/commands/BeautifyCommand.ts
  src/utils.ts
  test/commands/BeautifyCommand.spec.ts
  test/commands/__snapshots__/BeautifyCommand.spec.ts.snap
  test/fixtures/test1.js
  tslint.json
Labels: enhancement
